blogapp/accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

blogapp/articles/urls.py
from django.conf.urls import url
from . import views
from django.views.decorators.cache import cache_page

app_name = 'articles'

urlpatterns = [
    url(r'^$', views.article_list, name="list"),
    url(r'^create/$', views.article_create, name="create"),
    url(r'^(?P<slug>[\w-]+)/$', views.article_detail, name="detail"),
    url(r'^(?P<slug>[\w-]+)/comment/$', views.article_add_comment_to_post, name='add_comment_to_post'),
    url(r'^(?P<slug>[\w-]+)/$', views.cache_view, name='cache')

]

blogapp/blogapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^articles/', include('articles.urls')),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^about/$', views.about),
    url(r'^$', article_views.article_list, name="home"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/accounts/models.py
from django.db import models

# Create your models here.

blogapp/articles/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Article(models.Model):
    title = models.CharField(max_length=60)
    slug = models.SlugField()
    body = models.TextField(max_length=140)
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)
    author = models.ForeignKey(User, default=None)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'

class Comment(models.Model):
    post = models.ForeignKey(Article, related_name='comments',blank=True )
    author = models.CharField(max_length=100)
    body = models.TextField(null=True)
    created_date = models.DateTimeField(auto_now_add=True)
    approved_comment = models.BooleanField(default=False)

    def approve(self):
        self.approved_comment = True
        self.save()

    def __str__(self):
        return self.body

blogapp/articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'body', 'slug', 'thumb',]

class CommentForm(forms.ModelForm):

    class Meta:
        model = models.Comment
        fields = ( 'body',)

blogapp/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout

def signup_view(request):
    if request.method == 'POST':
         form = UserCreationForm(request.POST)
         if form.is_valid():
             user = form.save()
             #  log the user in
             login(request, user)
             return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', { 'form': form })

def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            # log the user in
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            else:
               return redirect('articles:list')
    else:
        form = AuthenticationForm()
    return render(request, 'accounts/login.html', { 'form': form })

def logout_view(request):
    if request.method == 'POST':
            logout(request)
            return redirect('articles:list')

blogapp/articles/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import Article
from django.contrib.auth.decorators import login_required
from . import forms
from django.shortcuts import get_object_or_404
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from django.utils.cache import patch_vary_headers


def article_list(request):
    articles = Article.objects.all().order_by('-date');
    return render(request, 'articles/article_list.html', { 'articles': articles })

def article_detail(request, slug):
    # return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', { 'article': article })

@login_required(login_url="/accounts/login/")
def article_create(request):
    if request.method == 'POST':
        form = forms.CreateArticle(request.POST, request.FILES)
        if form.is_valid():
            # save article to db
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:list')
    else:
        form = forms.CreateArticle()
    return render(request, 'articles/article_create.html', { 'form': form })

@login_required(login_url="/accounts/login/")
def article_add_comment_to_post(request, slug):
    #return HttpResponse(slug)
    article = Article.objects.get(slug=slug)
    if request.method == "POST":
        form = forms.CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = article
            comment.author = request.user
            comment.save()
            return redirect('articles:detail', slug=article.slug)
    else:
        form = forms.CommentForm()
    return render(request, 'articles/article_add_comment_to_post.html', {'form': form})

@cache_page(900,key_prefix='mycache') #will be catched for 15 mins 60*15
def cache_view(request):
    cache_key= Article.title
   # cache_time = 86400  
    data = cache.get(cache_key)
    if not data:
        article = Article()
        data = article.get_data()
        cache.set(cache_key, data)
    response=render(request,'articles/article_list.html')
    patch_vary_headers(response,['Cookie'])
    return response

blogapp/blogapp/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    # return HttpResponse('homepage')
    return render(request, 'homepage.html')

def about(request):
    # return HttpResponse('about')
    return render(request, 'about.html')

blogapp/accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Log in</h1>
    <form class="site-form" action="{% url 'accounts:login' %}" method="post">
        {% csrf_token %}
        {{ form }}
        {% if request.GET.next %}
            <input type="hidden" name="next" value="{{ request.GET.next }}" />
        {% endif %}
        <input type="submit" value="Login" />
    </form>
    <p>Not got an account? <a href="{% url 'accounts:signup' %}">Sign Up</a></p>
{% endblock %}

blogapp/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="{% url 'accounts:signup' %}" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

blogapp/articles/templates/articles/add_comment_to_post.html
{% extends 'blog/base.html' %}

{% block content %}
<div class="post-comment">

<h1>New comment</h1>
    <form method="POST" action="{% url 'articles:comments' %}" enctype="multipart/form-data">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>

 </div>
{% endblock %}

blogapp/articles/templates/articles/article_add_comment_to_post.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>New comment</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form }}
        <button type="submit" class="save btn btn-default">Send</button>
    </form>
{% endblock %}

blogapp/articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}

{% block content %}
    <div class="create-article">
        <h2>Create an Awesome New Article</h2>
        <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form }}
            <input type="submit" value="Create">
        </form>
    </div>
    <script src="/static/slugify.js"></script>
{% endblock %}

blogapp/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <img src="{{ article.thumb.url }}" />
        <h2>{{ article.title }}</h2>
        <h3>Written by <strong>{{ article.author.username }}</strong></h3>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>
</div>

<p><a class="btn btn-default" href="{% url 'articles:add_comment_to_post' slug=article.slug %}">Add comments</a></p>

<hr>

{% for comment in article.comments.all %}

    <div class="comment">
        <div class="date"> {{ comment.created_date }}</div>
        <strong>{{ comment.author }}</strong>
        <p>{{ comment.body|linebreaks }}</p>
<hr>
    </div>
{% empty %}
    <p>No comments here yet :(</p>
{% endfor %}

{% endblock %}

blogapp/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}
{% block content%}
    <h1>Articles Lists:</h1>
    <div class="articles">
    {% for article in articles %}
        <div class="article">
            <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
            <p>{{ article.snippet }}</p>
            <p>{{ article.date }}</p>
            <p class="author">added by {{ article.author.username }}</p>
            <p><a href="{% url 'articles:detail' slug=article.slug %}">Comments: {{ article.comments.count }}</a></p>
        </div>
    {% endfor %}
    </div>
{% endblock %}

blogapp/templates/about.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="wrapper">
    <h1>About Us</h1>
    <p>We like django.</p>
</div>
{% endblock %}

blogapp/templates/base_layout.html
{% load static from staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Django Blog Application</title>
        <link rel="stylesheet" href="{% static 'styles.css' %}">
    </head>
    <body>
        <header class="wrapper">
            <h1><a href="{% url 'home' %}"><img src="{% static 'logo.png' %}" alt="djangonautic" /></a></h1>
            <nav>
                <ul>
                    {% if user.is_authenticated %}
                    <li>
                        <form class="logout-link" action="{% url 'accounts:logout' %}" method="post">
                            {% csrf_token %}
                            <button type="submit">Logout</button>
                        </form>
                    </li>
                    <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
                    {% else %}
                    <li><a href="{% url 'accounts:login' %}">Login</a></li>
                    <li><a href="{% url 'accounts:signup' %}">Signup</a></li>
                    {% endif %}
                </ul>
            </nav>
        </header>
        <div class="wrapper">
            {% block content %}
            {% endblock %}
        </div>
    </body>
</html>